name: ci

on:
  push:
    branches: [ main ]

jobs:
  styx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: |
          nix-build site.nix

      - name: Deploy
        run: |
          sudo rm -rf /srv/clarelab/www/*
          cp -r result/* /srv/clarelab/www/