name: ci
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: sudo rm -rf /srv/clarelab/www/*
      - run: cp -r dist/* /srv/clarelab/www/