services:
  www:
    image: node:20-bookworm
    container_name: vps-clarelab-www
    working_dir: /workspace
    ports:
      - "8080:8080"
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        corepack enable &&
        corepack prepare pnpm@8.15.5 --activate &&
        pnpm install &&
        npx elm install elm/json &&
        pnpm dev --host 0.0.0.0 --port 8080
      "